(source "ELPA" "http://tromey.com/elpa/")
(source "MELPA" "http://melpa.org/packages/")
(source gnu)

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "avy")
(depends-on "cask")
(depends-on "coffee-mode")
(depends-on "company")
(depends-on "counsel")
(depends-on "counsel-projectile")
(depends-on "doom-themes")
(depends-on "evil")
(depends-on "evil-escape")
(depends-on "evil-leader")
(depends-on "evil-org")
(depends-on "evil-smartparens")
(depends-on "evil-surround")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "flx")
(depends-on "golden-ratio")
(depends-on "haml-mode")
(depends-on "ivy")
(depends-on "magit")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "projectile")
(depends-on "rspec-mode")
(depends-on "smartparens")
(depends-on "smex" :git "https://github.com/abo-abo/smex")
(depends-on "solarized-theme")
(depends-on "use-package")
(depends-on "wgrep-ag")
(depends-on "which-key")
(depends-on "yaml-mode")
